version: "3"
services:

   bot:
       build: .
       command: python bot.py
       depends_on:
         - database

   database:
     image: postgres:latest
     environment:
       POSTGRES_USER: "admin"
       POSTGRES_PASSWORD: "admin_password"
       POSTGRES_HOST: "postgres"
       POSTGRES_PORT: "5432"
       POSTGRES_DB: "db"
     ports:
     - "5432:5432"
